Repository scorelab/Bassa, pull requests merged in 2019-08, with the labels that each got.

#821 Improve documentation for Bassa
  README.md
Labels: GSoC-2019, enhancement

#782 Updated and working version of development dockerfile for Bassa UI
  ui/Dockerfile.dev
Labels: GSoC-2019, bug

#797 Implemented a working production UI dockerfile for Bassa
  ui/Dockerfile
Labels: GSoC-2019, bug

#754 Improved Travis CI builds for Bassa
  .travis.yml
Labels: GSoC-2019, enhancement

#789 Implemented a Dockerfile for Aria2c RPC server
  components/aria2c/Dockerfile
Labels: Feature, GSoC-2019

#793 Getting Bassa ready for container based deployment using docker-compose
  .gitignore
  components/core/dl.conf
  docker-compose.dev.yml
  downloads/data.txt
Labels: Feature, GSoC-2019, Release, suggestions needed

#824 Update docker labels, production docker-compose and simple fixes.
  README.md
  components/aria2c/Dockerfile
  components/core/Dockerfile
  components/core/Dockerfile.prod
  docker-compose.dev.yml
  docker-compose.yml
  ui/.dockerignore
  ui/Dockerfile
  ui/Dockerfile.dev
Labels: Feature, GSoC-2019, bug, enhancement

#808 Integrating Bassa with Storage Server (Minio)
  components/core/DownloadDaemon.py
  components/core/DownloadManager.py
  components/core/MinioHandler.py
  components/core/Server.py
  components/core/routes/Download.py
  db_schema/Bassa.sql
  setup.sh
  ui/src/app/admin/controllers/AdminCtrl.js
  ui/src/app/admin/services/AdminService.js
  ui/src/app/completed/controllers/TableCtrl.js
  ui/src/app/completed/services/tableService.js
  ui/src/app/views/admin.html
  ui/src/app/views/table.html
Labels: API, Feature, GSoC-2019, GoogleSummerOfCode, suggestions needed
