Repository scorelab/Bassa, pull requests merged in 2019-07, with the labels that each got.

#776 Updated dockerfile for Bassa API server with necessary changes and optimization
  components/core/.dockerignore
  components/core/Dockerfile
  components/core/setup.py
Labels: Feature, GSoC-2019, enhancement

#809 added authentication and tested POST, GET requests in the React app
  components/frontend-react/.env.sample
  components/frontend-react/package.json
  components/frontend-react/src/__tests__/__snapshots__/Appbar.test.js.snap
  components/frontend-react/src/components/Appbar.js
  components/frontend-react/src/components/UserSignup.js
  components/frontend-react/src/containers/LoginComponent.js
Labels: GSoC-2019, GoogleSummerOfCode, UI, enhancement

#812 completed routing in the application and added GET requests for displaying completed and queued downloads
  components/frontend-react/package.json
  components/frontend-react/src/App.js
  components/frontend-react/src/bassa.png
  components/frontend-react/src/components/Appbar.js
  components/frontend-react/src/components/BassaIntroBox.js
  components/frontend-react/src/components/CompletedFile.js
  components/frontend-react/src/containers/CompletedComponent.js
  components/frontend-react/src/containers/CompletedFileList.js
  components/frontend-react/src/containers/Dashboard.js
  components/frontend-react/src/containers/LoginComponent.js
  components/frontend-react/src/containers/QueuedComponent.js
  components/frontend-react/src/containers/QueuedFileList.js
  components/frontend-react/src/index.js
  components/frontend-react/src/stories/CompletedFileList.stories.js
Labels: Feature, GSoC-2019, GoogleSummerOfCode, UI, enhancement

#813 Integrated a WSGI (Gunicorn) to Bassa API server
  components/core/Dockerfile.prod
  components/core/requirements.txt
  components/core/supervisor_api.conf
  components/core/wsgi_conf.py
Labels: API, Feature, GSoC-2019, enhancement

#792 Defined endpoints for file compression and added missing imports in sender.py
  components/core/Server.py
  components/core/file_sender/sender.py
  components/core/routes/Download.py
Labels: API, GSoC-2019, bug
